//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWT_V2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GWT_V2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ab_Coaster_MachinegifGWT {
            get {
                object obj = ResourceManager.GetObject("Ab_Coaster_MachinegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ab_Coaster_MachineimgGWT {
            get {
                object obj = ResourceManager.GetObject("Ab_Coaster_MachineimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alternate_Leg_RaisesgifGWT {
            get {
                object obj = ResourceManager.GetObject("Alternate_Leg_RaisesgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alternate_Leg_RaisesimgGWT {
            get {
                object obj = ResourceManager.GetObject("Alternate_Leg_RaisesimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap armCirclesShouldersgifGWT {
            get {
                object obj = ResourceManager.GetObject("armCirclesShouldersgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap armCirclesShouldersimgGWT {
            get {
                object obj = ResourceManager.GetObject("armCirclesShouldersimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArnoldPressgifGWT {
            get {
                object obj = ResourceManager.GetObject("ArnoldPressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArnoldPressimgGWT {
            get {
                object obj = ResourceManager.GetObject("ArnoldPressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bandLatPulldowngifGWT {
            get {
                object obj = ResourceManager.GetObject("bandLatPulldowngifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bandLatPulldownimgGWT {
            get {
                object obj = ResourceManager.GetObject("bandLatPulldownimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barbell_Bench_PressgifGWT {
            get {
                object obj = ResourceManager.GetObject("Barbell_Bench_PressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barbell_Bench_PressimgGWT {
            get {
                object obj = ResourceManager.GetObject("Barbell_Bench_PressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barbell_DeadliftgifGWT {
            get {
                object obj = ResourceManager.GetObject("Barbell_DeadliftgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barbell_DeadliftimgGWT {
            get {
                object obj = ResourceManager.GetObject("Barbell_DeadliftimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barbell_Lateral_LungegifGWT {
            get {
                object obj = ResourceManager.GetObject("Barbell_Lateral_LungegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barbell_Lateral_LungeimgGWT {
            get {
                object obj = ResourceManager.GetObject("Barbell_Lateral_LungeimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BARBELL_SQUATgifGWT {
            get {
                object obj = ResourceManager.GetObject("BARBELL_SQUATgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BARBELL_SQUATimgGWT {
            get {
                object obj = ResourceManager.GetObject("BARBELL_SQUATimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barbellRowgifGWT {
            get {
                object obj = ResourceManager.GetObject("barbellRowgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barbellRowimgGWT {
            get {
                object obj = ResourceManager.GetObject("barbellRowimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bench_DipsgifGWT {
            get {
                object obj = ResourceManager.GetObject("Bench_DipsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bench_DipsimgGWT {
            get {
                object obj = ResourceManager.GetObject("Bench_DipsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bent_Over_Lateral_RaisegifGWT {
            get {
                object obj = ResourceManager.GetObject("Bent_Over_Lateral_RaisegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bent_Over_Lateral_RaiseimgGWT {
            get {
                object obj = ResourceManager.GetObject("Bent_Over_Lateral_RaiseimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BentOverRowsgifGWT {
            get {
                object obj = ResourceManager.GetObject("BentOverRowsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BentOverRowsimgGWT {
            get {
                object obj = ResourceManager.GetObject("BentOverRowsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bicycle_CrunchgifGWT {
            get {
                object obj = ResourceManager.GetObject("Bicycle_CrunchgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bicycle_CrunchimgGWT {
            get {
                object obj = ResourceManager.GetObject("Bicycle_CrunchimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blockIconGWT {
            get {
                object obj = ResourceManager.GetObject("blockIconGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blurred_bg {
            get {
                object obj = ResourceManager.GetObject("blurred bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bodyweight_hip_thrustgifGWT {
            get {
                object obj = ResourceManager.GetObject("bodyweight_hip_thrustgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bodyweight_hip_thrustimgGWT {
            get {
                object obj = ResourceManager.GetObject("bodyweight_hip_thrustimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bodyweight_Single_Leg_DeadliftgifGWT {
            get {
                object obj = ResourceManager.GetObject("Bodyweight_Single_Leg_DeadliftgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bodyweight_Single_Leg_DeadliftimgGWT {
            get {
                object obj = ResourceManager.GetObject("Bodyweight_Single_Leg_DeadliftimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cable_Rope_Overhead_Triceps_ExtensiongifGWT {
            get {
                object obj = ResourceManager.GetObject("Cable_Rope_Overhead_Triceps_ExtensiongifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cable_Rope_Overhead_Triceps_ExtensionimgGWT {
            get {
                object obj = ResourceManager.GetObject("Cable_Rope_Overhead_Triceps_ExtensionimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cable_Upper_Chest_CrossoversgifGWT {
            get {
                object obj = ResourceManager.GetObject("Cable_Upper_Chest_CrossoversgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cable_Upper_Chest_CrossoversimgGWT {
            get {
                object obj = ResourceManager.GetObject("Cable_Upper_Chest_CrossoversimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap carbon_next_outline {
            get {
                object obj = ResourceManager.GetObject("carbon_next-outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap carbon_next_outline1 {
            get {
                object obj = ResourceManager.GetObject("carbon_next-outline1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chestBellRowgifGWT {
            get {
                object obj = ResourceManager.GetObject("chestBellRowgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chestBellRowimgGWT {
            get {
                object obj = ResourceManager.GetObject("chestBellRowimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeBtn {
            get {
                object obj = ResourceManager.GetObject("closeBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cross_Body_Mountain_ClimbergifGWT {
            get {
                object obj = ResourceManager.GetObject("Cross_Body_Mountain_ClimbergifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cross_Body_Mountain_ClimberimgGWT {
            get {
                object obj = ResourceManager.GetObject("Cross_Body_Mountain_ClimberimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cross_CrunchgifGWT {
            get {
                object obj = ResourceManager.GetObject("Cross_CrunchgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cross_CrunchimgGWT {
            get {
                object obj = ResourceManager.GetObject("Cross_CrunchimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CrunchgifGWT {
            get {
                object obj = ResourceManager.GetObject("CrunchgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CrunchimgGWT {
            get {
                object obj = ResourceManager.GetObject("CrunchimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Curtsey_SquatgifGWT {
            get {
                object obj = ResourceManager.GetObject("Curtsey_SquatgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Curtsey_SquatimgGWT {
            get {
                object obj = ResourceManager.GetObject("Curtsey_SquatimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap curtsy_lungegifGWT {
            get {
                object obj = ResourceManager.GetObject("curtsy_lungegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap curtsy_lungeimgGWT {
            get {
                object obj = ResourceManager.GetObject("curtsy_lungeimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deadHanggifGWT {
            get {
                object obj = ResourceManager.GetObject("deadHanggifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deadHangimgGWT {
            get {
                object obj = ResourceManager.GetObject("deadHangimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deadliftgifGWT {
            get {
                object obj = ResourceManager.GetObject("deadliftgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deadliftimgGWT {
            get {
                object obj = ResourceManager.GetObject("deadliftimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Done {
            get {
                object obj = ResourceManager.GetObject("Done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Done__1_ {
            get {
                object obj = ResourceManager.GetObject("Done (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dragon_FlaggifGWT {
            get {
                object obj = ResourceManager.GetObject("Dragon_FlaggifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dragon_FlagimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dragon_FlagimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_4_Ways_Lateral_RaisegifGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_4_Ways_Lateral_RaisegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_4_Ways_Lateral_RaiseimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_4_Ways_Lateral_RaiseimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dumbbell_deadliftsgifGWT {
            get {
                object obj = ResourceManager.GetObject("dumbbell_deadliftsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dumbbell_deadliftsimgGWT {
            get {
                object obj = ResourceManager.GetObject("dumbbell_deadliftsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_FlygifGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_FlygifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_FlyimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_FlyimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_Goblet_SquatgifGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_Goblet_SquatgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_Goblet_SquatimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_Goblet_SquatimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_KickbackgifGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_KickbackgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_KickbackimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_KickbackimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_Lateral_RaisegifGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_Lateral_RaisegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_Lateral_RaiseimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_Lateral_RaiseimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dumbbell_lungesgifGWT {
            get {
                object obj = ResourceManager.GetObject("dumbbell_lungesgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dumbbell_lungesimgGWT {
            get {
                object obj = ResourceManager.GetObject("dumbbell_lungesimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_PressgifGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_PressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_PressimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_PressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_PullovergifGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_PullovergifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_PulloverimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_PulloverimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_Shoulder_PressgifGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_Shoulder_PressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_Shoulder_PressimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_Shoulder_PressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_SquatgifGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_SquatgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dumbbell_SquatimgGWT {
            get {
                object obj = ResourceManager.GetObject("Dumbbell_SquatimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dumbbell_sumo_deadliftgifGWT {
            get {
                object obj = ResourceManager.GetObject("dumbbell_sumo_deadliftgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dumbbell_sumo_deadliftimgGWT {
            get {
                object obj = ResourceManager.GetObject("dumbbell_sumo_deadliftimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dumbbellIconGwt {
            get {
                object obj = ResourceManager.GetObject("dumbbellIconGwt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit__1_ {
            get {
                object obj = ResourceManager.GetObject("Edit (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_black {
            get {
                object obj = ResourceManager.GetObject("eye black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_closed {
            get {
                object obj = ResourceManager.GetObject("eye closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_closed_black {
            get {
                object obj = ResourceManager.GetObject("eye-closed black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_open {
            get {
                object obj = ResourceManager.GetObject("eye open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap farmersWalkgifGWT {
            get {
                object obj = ResourceManager.GetObject("farmersWalkgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap farmersWalkimgGWT {
            get {
                object obj = ResourceManager.GetObject("farmersWalkimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap femaleGWT {
            get {
                object obj = ResourceManager.GetObject("femaleGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fluent_minimize_24_filled {
            get {
                object obj = ResourceManager.GetObject("fluent_minimize-24-filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Group_9 {
            get {
                object obj = ResourceManager.GetObject("Group 9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Group_91 {
            get {
                object obj = ResourceManager.GetObject("Group 91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GwtLogo_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("GwtLogo-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gymLoading {
            get {
                object obj = ResourceManager.GetObject("gymLoading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gymLoading2 {
            get {
                object obj = ResourceManager.GetObject("gymLoading2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap High_Cable_CrossovergifGWT {
            get {
                object obj = ResourceManager.GetObject("High_Cable_CrossovergifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap High_Cable_CrossoverimgGWT {
            get {
                object obj = ResourceManager.GetObject("High_Cable_CrossoverimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Incline_Barbell_Bench_PressgifGWT {
            get {
                object obj = ResourceManager.GetObject("Incline_Barbell_Bench_PressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Incline_Barbell_Bench_PressimgGWT {
            get {
                object obj = ResourceManager.GetObject("Incline_Barbell_Bench_PressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Incline_Chest_Fly_MachinegifGWT {
            get {
                object obj = ResourceManager.GetObject("Incline_Chest_Fly_MachinegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Incline_Chest_Fly_MachineimgGWT {
            get {
                object obj = ResourceManager.GetObject("Incline_Chest_Fly_MachineimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Incline_dumbbell_FlygifGWT {
            get {
                object obj = ResourceManager.GetObject("Incline_dumbbell_FlygifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Incline_dumbbell_FlyimgGWT {
            get {
                object obj = ResourceManager.GetObject("Incline_dumbbell_FlyimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jump_SquatgifGWT {
            get {
                object obj = ResourceManager.GetObject("Jump_SquatgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jump_SquatimgGWT {
            get {
                object obj = ResourceManager.GetObject("Jump_SquatimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kettlebell_Single_Leg_DeadliftgifGWT {
            get {
                object obj = ResourceManager.GetObject("Kettlebell_Single_Leg_DeadliftgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kettlebell_Single_Leg_DeadliftimgGWT {
            get {
                object obj = ResourceManager.GetObject("Kettlebell_Single_Leg_DeadliftimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kettlebell_SwingsgifGWT {
            get {
                object obj = ResourceManager.GetObject("Kettlebell_SwingsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kettlebell_SwingsimgGWT {
            get {
                object obj = ResourceManager.GetObject("Kettlebell_SwingsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap latPullDowngifGWT {
            get {
                object obj = ResourceManager.GetObject("latPullDowngifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap latPullDownimgGWT {
            get {
                object obj = ResourceManager.GetObject("latPullDownimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leg_CurlgifGWT {
            get {
                object obj = ResourceManager.GetObject("Leg_CurlgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leg_CurlimgGWT {
            get {
                object obj = ResourceManager.GetObject("Leg_CurlimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leg_PressgifGWT {
            get {
                object obj = ResourceManager.GetObject("Leg_PressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leg_PressimgGWT {
            get {
                object obj = ResourceManager.GetObject("Leg_PressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lever_Overhand_Triceps_DipgifGWT {
            get {
                object obj = ResourceManager.GetObject("Lever_Overhand_Triceps_DipgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lever_Overhand_Triceps_DipimgGWT {
            get {
                object obj = ResourceManager.GetObject("Lever_Overhand_Triceps_DipimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loadingAnimationGWT {
            get {
                object obj = ResourceManager.GetObject("loadingAnimationGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loadingAnimationGWT1 {
            get {
                object obj = ResourceManager.GetObject("loadingAnimationGWT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loadingAnimationGWT2 {
            get {
                object obj = ResourceManager.GetObject("loadingAnimationGWT2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logout_Rounded_Left {
            get {
                object obj = ResourceManager.GetObject("Logout Rounded Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logout_Rounded_Left__1_ {
            get {
                object obj = ResourceManager.GetObject("Logout Rounded Left (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logout_Rounded_Left1 {
            get {
                object obj = ResourceManager.GetObject("Logout Rounded Left1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Low_Cable_CrossovergifGWT {
            get {
                object obj = ResourceManager.GetObject("Low_Cable_CrossovergifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Low_Cable_CrossoverimgGWT {
            get {
                object obj = ResourceManager.GetObject("Low_Cable_CrossoverimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Machine_FlygifGWT {
            get {
                object obj = ResourceManager.GetObject("Machine_FlygifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Machine_FlyimgGWT {
            get {
                object obj = ResourceManager.GetObject("Machine_FlyimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Machine_Shoulder_PressgifGWT {
            get {
                object obj = ResourceManager.GetObject("Machine_Shoulder_PressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Machine_Shoulder_PressimgGWT {
            get {
                object obj = ResourceManager.GetObject("Machine_Shoulder_PressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MacOS_Minimize {
            get {
                object obj = ResourceManager.GetObject("MacOS Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maleGWT {
            get {
                object obj = ResourceManager.GetObject("maleGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap manRunning {
            get {
                object obj = ResourceManager.GetObject("manRunning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Medicine_Ball_Overhead_ThrowgifGWT {
            get {
                object obj = ResourceManager.GetObject("Medicine_Ball_Overhead_ThrowgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Medicine_Ball_Overhead_ThrowimgGWT {
            get {
                object obj = ResourceManager.GetObject("Medicine_Ball_Overhead_ThrowimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Medicine_Ball_Rotational_ThrowgifGWT {
            get {
                object obj = ResourceManager.GetObject("Medicine_Ball_Rotational_ThrowgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Medicine_Ball_Rotational_ThrowimgGWT {
            get {
                object obj = ResourceManager.GetObject("Medicine_Ball_Rotational_ThrowimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mingcute_back_fill {
            get {
                object obj = ResourceManager.GetObject("mingcute_back-fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimizeRed {
            get {
                object obj = ResourceManager.GetObject("minimizeRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MJL_CombinationMark {
            get {
                object obj = ResourceManager.GetObject("MJL_CombinationMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MJL_CombinationMark_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("MJL_CombinationMark-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MJL_CombinationMark_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("MJL_CombinationMark-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mountain_climbergifGWT {
            get {
                object obj = ResourceManager.GetObject("Mountain_climbergifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mountain_climberimgGWT {
            get {
                object obj = ResourceManager.GetObject("Mountain_climberimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap muscleAbsGWT {
            get {
                object obj = ResourceManager.GetObject("muscleAbsGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap muscleArmGWT {
            get {
                object obj = ResourceManager.GetObject("muscleArmGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap muscleBackGWT {
            get {
                object obj = ResourceManager.GetObject("muscleBackGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap muscleButtGWT {
            get {
                object obj = ResourceManager.GetObject("muscleButtGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap muscleChestGWT {
            get {
                object obj = ResourceManager.GetObject("muscleChestGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap muscleFull {
            get {
                object obj = ResourceManager.GetObject("muscleFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap muscleLegGWT {
            get {
                object obj = ResourceManager.GetObject("muscleLegGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap muscleShoulderGWT {
            get {
                object obj = ResourceManager.GetObject("muscleShoulderGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Oblique_Floor_CrunchesgifGWT {
            get {
                object obj = ResourceManager.GetObject("Oblique_Floor_CrunchesgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Oblique_Floor_CrunchesimgGWT {
            get {
                object obj = ResourceManager.GetObject("Oblique_Floor_CrunchesimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap one_arm_Cable_Lateral_RaisegifGWT {
            get {
                object obj = ResourceManager.GetObject("one_arm_Cable_Lateral_RaisegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap one_arm_Cable_Lateral_RaiseimgGWT {
            get {
                object obj = ResourceManager.GetObject("one_arm_Cable_Lateral_RaiseimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap One_Arm_Reverse_Push_DowngifGWT {
            get {
                object obj = ResourceManager.GetObject("One_Arm_Reverse_Push_DowngifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap One_Arm_Reverse_Push_DownimgGWT {
            get {
                object obj = ResourceManager.GetObject("One_Arm_Reverse_Push_DownimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap One_arm_triceps_pushdowngifGWT {
            get {
                object obj = ResourceManager.GetObject("One_arm_triceps_pushdowngifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap One_arm_triceps_pushdownimgGWT {
            get {
                object obj = ResourceManager.GetObject("One_arm_triceps_pushdownimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oneArmDumbbellRowgifGWT {
            get {
                object obj = ResourceManager.GetObject("oneArmDumbbellRowgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oneArmDumbbellRowimgGWT {
            get {
                object obj = ResourceManager.GetObject("oneArmDumbbellRowimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Overhead_PressgifGWT {
            get {
                object obj = ResourceManager.GetObject("Overhead_PressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Overhead_PressimgGWT {
            get {
                object obj = ResourceManager.GetObject("Overhead_PressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pec_Deck_FlygifGWT {
            get {
                object obj = ResourceManager.GetObject("Pec_Deck_FlygifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pec_Deck_FlyimgGWT {
            get {
                object obj = ResourceManager.GetObject("Pec_Deck_FlyimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plankgifGWT {
            get {
                object obj = ResourceManager.GetObject("plankgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plankimgGWT {
            get {
                object obj = ResourceManager.GetObject("plankimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PullUpsgifGWT {
            get {
                object obj = ResourceManager.GetObject("PullUpsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PullUpsimgGWT {
            get {
                object obj = ResourceManager.GetObject("PullUpsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PushdowngifGWT {
            get {
                object obj = ResourceManager.GetObject("PushdowngifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PushdownimgGWT {
            get {
                object obj = ResourceManager.GetObject("PushdownimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap renegadeRowsgifGWT {
            get {
                object obj = ResourceManager.GetObject("renegadeRowsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap renegadeRowsimgGWT {
            get {
                object obj = ResourceManager.GetObject("renegadeRowsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Replace {
            get {
                object obj = ResourceManager.GetObject("Replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reportIconGWT {
            get {
                object obj = ResourceManager.GetObject("reportIconGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reverse_crunchGWT {
            get {
                object obj = ResourceManager.GetObject("Reverse_crunchGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reverse_Lunge_KneegifGWT {
            get {
                object obj = ResourceManager.GetObject("Reverse_Lunge_KneegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reverse_Lunge_KneeimgGWT {
            get {
                object obj = ResourceManager.GetObject("Reverse_Lunge_KneeimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReverseCrunchGwt {
            get {
                object obj = ResourceManager.GetObject("ReverseCrunchGwt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seated_Behind_the_Neck_PressgifGWT {
            get {
                object obj = ResourceManager.GetObject("Seated_Behind_the_Neck_PressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seated_Behind_the_Neck_PressimgGWT {
            get {
                object obj = ResourceManager.GetObject("Seated_Behind_the_Neck_PressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seated_Bench_Leg_Pull_ingifGWT {
            get {
                object obj = ResourceManager.GetObject("Seated_Bench_Leg_Pull_ingifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seated_Bench_Leg_Pull_inimgGWT {
            get {
                object obj = ResourceManager.GetObject("Seated_Bench_Leg_Pull_inimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seated_Dumbbell_Triceps_ExtensiongifGWT {
            get {
                object obj = ResourceManager.GetObject("Seated_Dumbbell_Triceps_ExtensiongifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seated_Dumbbell_Triceps_ExtensionimgGWT {
            get {
                object obj = ResourceManager.GetObject("Seated_Dumbbell_Triceps_ExtensionimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seated_Shoulder_PressgifGWT {
            get {
                object obj = ResourceManager.GetObject("Seated_Shoulder_PressgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seated_Shoulder_PressimgGWT {
            get {
                object obj = ResourceManager.GetObject("Seated_Shoulder_PressimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seatedCableRowsgifGWT {
            get {
                object obj = ResourceManager.GetObject("seatedCableRowsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seatedCableRowsimgGWT {
            get {
                object obj = ResourceManager.GetObject("seatedCableRowsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settingIconGWT {
            get {
                object obj = ResourceManager.GetObject("settingIconGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap side_arm_raisegifGWT {
            get {
                object obj = ResourceManager.GetObject("side_arm_raisegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap side_arm_raiseimgGWT {
            get {
                object obj = ResourceManager.GetObject("side_arm_raiseimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Side_Lying_ClamgifGWT {
            get {
                object obj = ResourceManager.GetObject("Side_Lying_ClamgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Side_Lying_ClamimgGWT {
            get {
                object obj = ResourceManager.GetObject("Side_Lying_ClamimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sign_Up {
            get {
                object obj = ResourceManager.GetObject("Sign Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Standing_Cable_CrunchgifGWT {
            get {
                object obj = ResourceManager.GetObject("Standing_Cable_CrunchgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Standing_Cable_CrunchimgGWT {
            get {
                object obj = ResourceManager.GetObject("Standing_Cable_CrunchimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Standing_Hip_Abduction_1gifGWT {
            get {
                object obj = ResourceManager.GetObject("Standing_Hip_Abduction_1gifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Standing_Hip_Abduction_1imgGWT {
            get {
                object obj = ResourceManager.GetObject("Standing_Hip_Abduction_1imgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Standing_Hip_ExtensiongifGWT {
            get {
                object obj = ResourceManager.GetObject("Standing_Hip_ExtensiongifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Standing_Hip_ExtensionimgGWT {
            get {
                object obj = ResourceManager.GetObject("Standing_Hip_ExtensionimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Standing_Leg_CirclesgifGWT {
            get {
                object obj = ResourceManager.GetObject("Standing_Leg_CirclesgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Standing_Leg_CirclesimgGWT {
            get {
                object obj = ResourceManager.GetObject("Standing_Leg_CirclesimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Static_LungegifGWT {
            get {
                object obj = ResourceManager.GetObject("Static_LungegifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Static_LungeimgGWT {
            get {
                object obj = ResourceManager.GetObject("Static_LungeimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Triceps_dips_on_floorsgifGWT {
            get {
                object obj = ResourceManager.GetObject("Triceps_dips_on_floorsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Triceps_dips_on_floorsimgGWT {
            get {
                object obj = ResourceManager.GetObject("Triceps_dips_on_floorsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Triceps_DipsgifGWT {
            get {
                object obj = ResourceManager.GetObject("Triceps_DipsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Triceps_DipsimgGWT {
            get {
                object obj = ResourceManager.GetObject("Triceps_DipsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap userIconGWT {
            get {
                object obj = ResourceManager.GetObject("userIconGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wall_Push_upsgifGWT {
            get {
                object obj = ResourceManager.GetObject("Wall_Push_upsgifGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wall_Push_upsimgGWT {
            get {
                object obj = ResourceManager.GetObject("Wall_Push_upsimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wall_SitimgGWT {
            get {
                object obj = ResourceManager.GetObject("Wall_SitimgGWT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warningGif {
            get {
                object obj = ResourceManager.GetObject("warningGif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
